version: "3"

services:
  nitter:
    image: zedeus/nitter:latest
    container_name: nitter
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./nitter-config:/config
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: nitter-redis
    restart: unless-stopped
